# -*- coding: utf-8 -*-
"""
Created on 2021-04-08 12:20:22
---------
@summary:
---------
@author: xingag
"""

from feapder import Item


class TopicItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i topic.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None  # 文章标题
        self.auth = None  # 作者
        self.like_count = 0  # 喜欢数
        self.collection = 0  # 收藏数
        self.comment = 0  # 评论数
